### Defining Computation Graphs in TensorFlow

The examples in said chapter.

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
a = tf.constant(5, name="input_a")
b = tf.constant(3, name="input_b")
c = tf.mul(a,b, name="mul_c")
d = tf.add(a,b, name="add_d")
e = tf.add(c,d, name="add_e")

In [5]:
sess = tf.Session()
sess.run(e)

23

In [6]:
sess.run(c)

15

In [8]:
output = sess.run(e)
print(output, type(output))
writer = tf.train.SummaryWriter('./my_graph', sess.graph)
print(writer)

23 <class 'numpy.int32'>


In [10]:
writer.close()
sess.close()

In [11]:
i = tf.constant([5,3], name="input_i")
b = tf.reduce_prod(a, name="prod_b")
c = tf.reduce_sum(a, name="sum_c")
d = tf.add(b,c, name="add_d")
print(i, type(i))

Tensor("input_i:0", shape=(2,), dtype=int32) <class 'tensorflow.python.framework.ops.Tensor'>


In [13]:
import numpy as np  # Don't forget to import NumPy!

# 0-D Tensor with 32-bit integer data type
t_0 = np.array(50, dtype=np.int32)

# 1-D Tensor with byte string data type
# Note: don't explicitly specify dtype when using strings in NumPy
t_1 = np.array([b"apple", b"peach", b"grape"])

# 1-D Tensor with boolean data type
t_2 = np.array([[True, False, False],
                [False, False, True],
                [False, True, False]], dtype=np.bool)

# 3-D Tensor with 64-bit integer data type
t_3 = np.array([[ [0, 0], [0, 1], [0, 2] ],
                [ [1, 0], [1, 1], [1, 2] ],
                [ [2, 0], [2, 1], [2, 2] ]], dtype=np.int64)

print(np.int32 == tf.int32)

True


In [14]:
## Shapes

# Find the shape of the mystery tensor
shape = tf.shape(i, name="input_shape")
print(shape, type(shape))

Tensor("input_shape:0", shape=(1,), dtype=int32) <class 'tensorflow.python.framework.ops.Tensor'>


In [17]:
## Does this work?!

# Initialize some tensors to use in computation
a = np.array([2, 3], dtype=np.int32)
b = np.array([4, 5], dtype=np.int32)

# Use `tf.add()` to initialize an "add" Operation
# The variable `c` will be a handle to the Tensor output of this Op
c = tf.add(a, b, name="my_add_op")

print(type(a), type(b), type(c))
sess2 = tf.Session()
print(sess2.run(c))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'tensorflow.python.framework.ops.Tensor'>
[6 8]


#### More about graphs

In [18]:
# Create a new graph:
g = tf.Graph()

with g.as_default():
    # Create Operations as usual; they will be added to graph `g`
    a = tf.add(2, 3, name='g_add')
    
# Placed in the default graph
in_default_graph = tf.add(1, 2, name='def_add')

# Placed in graph `g`
with g.as_default():
    in_graph_g = tf.mul(2, 3, name='g_mul')
    
default_graph = tf.get_default_graph()

#### Feed dict

In [21]:
# Create Operations, Tensors, etc (using the default graph)
a = tf.add(2, 5)
b = tf.mul(a, 3)

# Start up a `Session` using the default graph
sess = tf.Session()

# Run the vanilla session
print('Vanilla: {}'.format(sess.run(b)))

# Define a dictionary that says to replace the value of `a` with 15
replace_dict = {a: 15}

# Run the session, passing in `replace_dict` as the value to `feed_dict`
print('Replaced: {}'.format(sess.run(b, feed_dict=replace_dict)))

sess.close()

Vanilla: 21
Replaced: 45


#### Tensor.eval()

In [25]:
# Define simple constant
a = tf.constant(5)

# Open up a Session
sess = tf.Session()

# Use the Session as a default inside of `with` block
with sess.as_default():
    print(a.eval())

# Have to close Session manually.
sess.close()

5


#### Placeholders

In [27]:
# Creates a placeholder vector of length 2 with data type int32
a = tf.placeholder(tf.int32, shape=[2], name="my_input")

# Use the placeholder as if it were any other Tensor object
b = tf.reduce_prod(a, name="prod_b")
c = tf.reduce_sum(a, name="sum_c")

# Finish off the graph
d = tf.add(b, c, name="add_d")

# Open a TensorFlow Session
with tf.Session() as sess:
    
    # Create a dictionary to pass into `feed_dict`
    # Key: `a`, the handle to the placeholder's output Tensor
    # Value: A vector with value [5, 3] and int32 data type
    input_dict = {a: np.array([5, 3], dtype=np.int32)}
    
    # Fetch the value of `d`, feeding the values of `input_vector` into `a`
    print('d={}'.format(sess.run(d, feed_dict=input_dict)))

d=23


#### Variables

In [31]:
# Pass in a starting value of three for the variable
my_var = tf.Variable(3, name="my_variable")

add = tf.add(5, my_var)
mul = tf.mul(8, my_var)

# 2x2 matrix of zeros
zeros = tf.zeros([2, 2])

# vector of length 6 of ones
ones = tf.ones([6])

# 3x3x3 Tensor of random uniform values between 0 and 10
uniform = tf.random_uniform([3, 3, 3], minval=0, maxval=10)

# 3x3x3 Tensor of normally distributed numbers; mean 0 and standard devia
# tion 2
normal = tf.random_normal([3, 3, 3], mean=0.0, stddev=2.0)

# No values below 3.0 or above 7.0 will be returned in this Tensor
trunc = tf.truncated_normal([2, 2], mean=5.0, stddev=1.0)

# Default value of mean=0.0
# Default value of stddev=1.0
random_var = tf.Variable(tf.truncated_normal([2, 2]))

with tf.Session() as sess:
    print('zeros = ', sess.run(zeros))
    print('ones = ', sess.run(ones))
    print('uniform = ', sess.run(uniform))
    print('normal = ', sess.run(normal))
    print('trunc = ', sess.run(trunc))
    
    # Variables need initialization
    sess.run(tf.initialize_all_variables())
    print('random_var = ', sess.run(random_var))

zeros =  [[ 0.  0.]
 [ 0.  0.]]
ones =  [ 1.  1.  1.  1.  1.  1.]
uniform =  [[[ 9.90992069  2.13805079  9.66162491]
  [ 3.07296634  8.87727547  1.289047  ]
  [ 2.024405    6.0967207   8.25237179]]

 [[ 4.2806921   2.53113627  6.10365963]
  [ 8.92438507  7.37248993  1.08124971]
  [ 6.50774384  8.79329491  9.58144188]]

 [[ 4.82066059  7.06784487  8.19956398]
  [ 5.92780018  6.06400967  2.10077167]
  [ 2.97242045  9.59724045  8.19795513]]]
normal =  [[[-2.27528453  3.1213069   2.73794055]
  [ 2.93256831  0.37871492  0.75476038]
  [-0.24290156 -1.38127148  4.80996466]]

 [[ 1.32689667 -3.00137544 -0.04421335]
  [-1.39376903 -1.45173824 -0.74971473]
  [ 2.38709521  2.34441972  2.24946547]]

 [[-3.604743    1.176844   -1.22946692]
  [-0.57156056 -0.13345022 -0.28318942]
  [ 1.29720473 -2.02519631  0.75045985]]]
trunc =  [[ 5.16969872  5.17834234]
 [ 3.23011303  3.36001062]]
random_var =  [[ 0.10104871 -0.17173322]
 [-1.01679921 -0.17740199]]


In [35]:
# No need to initializes everything
var1 = tf.Variable(0, name="initialize_me")
var2 = tf.Variable(1, name="no_initialization")
init = tf.initialize_variables([var1], name="init_var1")
with tf.Session() as sess:
    sess.run(init)
    print(var1.eval())

0


##### Changing variables

In [36]:
# Create variable with starting value of 1
my_var = tf.Variable(1)

# Create an operation that multiplies the variable by 2 each time it is run
my_var_times_two = my_var.assign(my_var * 2)

# Initialization operation
init = tf.initialize_all_variables()

# Start a session
with tf.Session() as sess:
    # Initialize variable
    sess.run(init)
    
    # Multiply variable by two and return it
    print('First run: ', sess.run(my_var_times_two))

    # Multiply again
    print('Second run: ', sess.run(my_var_times_two))
    
    # Increment by 1
    print('After inc: ', sess.run(my_var.assign_add(1)))

    # Decrement by 2
    print('After dec: ', sess.run(my_var.assign_sub(2)))

First run:  2
Second run:  4
After inc:  5
After dec:  3


In [41]:
## Variables values are maintained by the session
# Create Ops
my_var = tf.Variable(0)
init = tf.initialize_all_variables()

# Start Sessions
sess1 = tf.Session()
sess2 = tf.Session()

# Initialize Variable in sess1, and increment value of my_var in that Session
sess1.run(init)
print('s1 + 5: ', sess1.run(my_var.assign_add(5)))

# Do the same with sess2, but use a different increment value
sess2.run(init)
print('s2 + 2: ', sess2.run(my_var.assign_add(2)))

# Can increment the Variable values in each Session independently
print('s1 ++ 5: ', sess1.run(my_var.assign_add(5)))

print('s2 ++ 2: ', sess2.run(my_var.assign_add(2)))

# Reset the Variable to 0, its initial value
sess1.run(init)
print('s1 reset: ', my_var.eval(sess1), sess1.run(my_var))

sess1.close()
sess2.close()

s1 + 5:  5
s2 + 2:  2
s1 ++ 5:  10
s2 ++ 2:  4
s1 reset:  0 0


##### Scopes

In [2]:
import tensorflow as tf

with tf.name_scope("Scope_A"):
    a = tf.add(1, 2, name="A_add")
    b = tf.mul(a, 3, name="A_mul")
    
with tf.name_scope("Scope_B"):
    c = tf.add(4, 5, name="B_add")
    d = tf.mul(c, 6, name="B_mul")
    
e = tf.add(b, d, name="output")

writer = tf.train.SummaryWriter('./boards/name_scope_1', graph=tf.get_default_graph())
writer.close()

In [4]:
graph = tf.Graph()

with graph.as_default():
    in_1 = tf.placeholder(tf.float32, shape=[], name="input_a")
    in_2 = tf.placeholder(tf.float32, shape=[], name="input_b")
    const = tf.constant(3, dtype=tf.float32, name="static_value")
    
    with tf.name_scope("Transformation"):
        with tf.name_scope("A"):
            A_mul = tf.mul(in_1, const)
            A_out = tf.sub(A_mul, in_1)
            
        with tf.name_scope("B"):
            B_mul = tf.mul(in_2, const)
            B_out = tf.sub(B_mul, in_2)
            
        with tf.name_scope("C"):
            C_div = tf.div(A_out, B_out)
            C_out = tf.add(C_div, const)

        with tf.name_scope("D"):
            D_div = tf.div(B_out, A_out)
            D_out = tf.add(D_div, const)
        
    out = tf.maximum(C_out, D_out)
    
writer = tf.train.SummaryWriter('./boards/name_scope_2', graph=graph)
writer.close()

In [11]:
with tf.Session(graph=graph) as sess:
    out_res, A_out_res, B_out_res, C_out_res, D_out_res = sess.run(
        [out, A_out, B_out, C_out, D_out], feed_dict={in_1: 5, in_2: 4})
    print('out {}, A_out {}, B_out {}, C_out {}, D_out {}'.format(
            out_res, A_out_res, B_out_res, C_out_res, D_out_res))

out 4.25, A_out 10.0, B_out 8.0, C_out 4.25, D_out 3.799999952316284


### Exercise

In [31]:
graph = tf.Graph()

with graph.as_default():
    with tf.name_scope('variables'):
        # Variable to keep track of how many times the graph has been run
        global_step = tf.Variable(0, dtype=tf.int32, trainable=False, name='global_step')
        # Variable that keeps track of the sum of all output values over time
        total_output = tf.Variable(0, dtype=tf.float32, trainable=False, name='total_output')
        
    with tf.name_scope('transformation'):
        # Separate input layer
        with tf.name_scope('input'):
            # Create input placeholder- takes in a Vector
            a = tf.placeholder(tf.float32, shape=[None], name='input_a')
            
        # Separate middle layer
        with tf.name_scope('middle'):
            b = tf.reduce_prod(a, name='product_b')
            c = tf.reduce_sum(a, name='sum_c')
            
        # Separate output layer
        with tf.name_scope('output'):
            output = tf.add(b, c, name='output')
        
        with tf.name_scope('update'):
            # Increments the total_output Variable by the latest output
            update_total = total_output.assign_add(output)
            # Increments the above `global_step` Variable, should be run whenever the graph is run
            increment_step = global_step.assign_add(1)
            
        with tf.name_scope('summaries'):
            avg = tf.div(update_total, tf.cast(increment_step, tf.float32), name='average')
            
            # Creates summaries for output node
            tf.scalar_summary(b'Output', output, name='output_summary')
            tf.scalar_summary(b'Sum of outputs', update_total, name='total_summary')
            tf.scalar_summary(b'Average of outputs', avg, name='average_summary')
            
        with tf.name_scope('global_ops'):
            # Initialization Op
            init = tf.initialize_all_variables()
            # Merge all summaries into one Op
            merged_summaries = tf.merge_all_summaries()
            
# Not a with, so that we can execute the graph again and again
sess = tf.Session(graph=graph)
writer = tf.train.SummaryWriter('./boards/improved_graph', graph)
sess.run(init)

def summary_to_dict(summary_str):
    """Converts the stupid summary byte string into a dictionary."""
    summary_proto = tf.Summary()
    summary_proto.ParseFromString(summary_str)
    return {val.tag: val.simple_value for val in summary_proto.value}

def run_graph(session, input_tensor):
    feed_dict = {a: input_tensor}
    out, step, summary = sess.run([output, increment_step, merged_summaries],
                                feed_dict=feed_dict)
    print(out, step, summary_to_dict(summary))
    writer.add_summary(summary, global_step=step)
    
def run_transformation(session, input_tensor):
    # Does not run the updates and summaries; let's see if they are run automatically
    feed_dict = {a: input_tensor}
    out = sess.run(output, feed_dict=feed_dict)
    print(out)

In [32]:
run_transformation(sess, [2,8])
run_graph(sess, [2,8])
run_transformation(sess, [2,8])
run_transformation(sess, [2,8])
run_graph(sess, [2,8])
run_graph(sess, [2,8])

26.0
26.0 1 {'Average of outputs': 26.0, 'Sum of outputs': 26.0, 'Output': 26.0}
26.0
26.0
26.0 2 {'Average of outputs': 26.0, 'Sum of outputs': 52.0, 'Output': 26.0}
26.0 3 {'Average of outputs': 26.0, 'Sum of outputs': 78.0, 'Output': 26.0}


In [33]:
writer.flush()
writer.close()
sess.close()